In [1]:
import numpy as np
import pandas as pd
%matplotlib inline

In [2]:
df = pd.read_csv('insurance_data.csv')

In [3]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [4]:
df.shape

(28, 3)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age', 'affordibility']], df.bought_insurance, test_size=0.2, random_state = 42)

In [6]:
len(X_train)

22

In [7]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100  

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [8]:
X_train_scaled

age  affordibility
17  0.58              1
22  0.40              1
11  0.28              1
13  0.29              0
15  0.55              1
1   0.25              0
4   0.46              1
5   0.56              1
2   0.47              1
16  0.25              0
23  0.45              1
3   0.52              0
26  0.23              1
24  0.50              1
18  0.19              0
27  0.46              1
20  0.21              1
7   0.60              0
10  0.18              1
14  0.49              1
19  0.18              1
6   0.55              0

In [9]:
from tensorflow import keras
model = keras.Sequential([
    keras.layers.Dense(1, activation='sigmoid', input_shape=(2,), kernel_initializer = 'ones', bias_initializer = 'zeros'),
])

model.compile(optimizer='adam',
              loss = 'binary_crossentropy',
              metrics = ['accuracy'])
model.fit(X_train_scaled, y_train, epochs=5000)

Epoch 1/5000


c:\Users\AliRaza\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5000 - loss: 0.7428
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7424
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5000 - loss: 0.7420
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.7416
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5000 - loss: 0.7411
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.7407
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.7403
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.7399
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5000 - loss: 0.7395
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.7390
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.7386
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss

In [25]:
model.evaluate(X_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.2647


[0.26470306515693665, 1.0]

In [26]:
X_test_scaled

age  affordibility
9   0.61              1
25  0.54              1
8   0.62              1
21  0.26              0
0   0.22              1
12  0.27              0

In [27]:
y_pred = model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step


In [28]:
coef, intercept = model.get_weights()

In [29]:
coef, intercept 

(array([[5.018309 ],
        [1.1966311]], dtype=float32),
 array([-2.766541], dtype=float32))

In [30]:
def sigmoid(x):
    import math
    return 1 / (1 + math.exp(-x))

In [31]:
sigmoid(2)

0.8807970779778823

In [32]:
def pred_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

In [33]:
pred_function(0.54, 1)

C:\Users\AliRaza\AppData\Local\Temp\ipykernel_19112\3918314859.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))


0.7576754121671682

In [34]:
def log_loss(y_true, y_pred):
    epsilon = 1e-15
    y_pred_new = [max(i, epsilon) for i in y_pred]
    y_pred_new = [min(i, 1-epsilon) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new) + (1 - y_true)*np.log(1 - y_pred_new))

In [35]:
def sigmoid_numpy(X):
    return 1/(1 + np.exp(-X))

In [36]:
sigmoid_numpy(np.array([12, 0, 1]))


array([0.99999386, 0.5       , 0.73105858])

In [37]:
def gradient_descent(age, affordibility, y_true, epochs, loss_thresold):
    w1 = w2 = 1
    bias = 0
    rate = 0.5
    n = len(age)
    for i in range(epochs):
        weighted_sum = w1 * age + w2 * affordibility + bias
        y_pred = sigmoid_numpy(weighted_sum)
        
        loss = log_loss(y_true, y_pred)
        
        w1d = (1/n)*np.dot(np.transpose(age), (y_pred - y_true))
        w2d = (1/n)*np.dot(np.transpose(affordibility), (y_pred - y_true))
        bias_d = np.mean(y_pred - y_true)

        w1 = w1 - rate * w1d
        w2 = w2 - rate * w2d
        bias = bias - rate * bias_d

        print(f'Epoch:{i}, w1:, {w1}, w2:, {w2}, bias:, {bias}, loss:, {loss}')

        if loss <= loss_thresold:
            break

    return w1, w2, bias


In [38]:
gradient_descent(X_train_scaled['age'], X_train_scaled['affordibility'], y_train, 1000, 0.4923)

Epoch:0, w1:, 0.9736899318847281, w2:, 0.931388810977659, bias:, -0.11748951666770448, loss:, 0.7428288579142563
Epoch:1, w1:, 0.9536535852311093, w2:, 0.8740290167758512, bias:, -0.21881533456146035, loss:, 0.7072146449948487
Epoch:2, w1:, 0.9393731039296968, w2:, 0.8271852202997496, bias:, -0.3053620401943441, loss:, 0.6814881914786812
Epoch:3, w1:, 0.930193258899806, w2:, 0.7897792032048467, bias:, -0.37884372361582785, loss:, 0.6633428084673968
Epoch:4, w1:, 0.9254091137248937, w2:, 0.7605726653866934, bias:, -0.441082368200183, loss:, 0.650742850709519
Epoch:5, w1:, 0.9243325693598606, w2:, 0.738313053647322, bias:, -0.4938425798625155, loss:, 0.6420508089402462
Epoch:6, w1:, 0.9263332963572349, w2:, 0.7218280753843739, bias:, -0.5387319906498417, loss:, 0.6360356979531206
Epoch:7, w1:, 0.9308580975636879, w2:, 0.7100747303660235, bias:, -0.5771558825717441, loss:, 0.631816485354411
Epoch:8, w1:, 0.9374354910317361, w2:, 0.7021560855322683, bias:, -0.6103083840841516, loss:, 0.628

(5.0147687108051695, 1.227094212784905, -2.7982358620493586)

In [39]:
coef, intercept

(array([[5.018309 ],
        [1.1966311]], dtype=float32),
 array([-2.766541], dtype=float32))

# `Building NN from Scratch`

In [51]:
class myNN:
    def __init__(self):
        self.w1 = 1
        self.w2 = 1
        self.bias = 0

    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'], X['affordibility'], y, epochs, loss_thresold)


    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age, affordibility, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordibility + bias
            y_pred = sigmoid_numpy(weighted_sum)
            
            loss = log_loss(y_true, y_pred)
            
            w1d = (1/n)*np.dot(np.transpose(age), (y_pred - y_true))
            w2d = (1/n)*np.dot(np.transpose(affordibility), (y_pred - y_true))
            bias_d = np.mean(y_pred - y_true)

            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d

            if i%50 == 0:
                print(f'Epoch:{i}, w1:, {w1}, w2:, {w2}, bias:, {bias}, loss:, {loss}')

            if loss <= loss_thresold:
                print(f'Epoch:{i}, w1:, {w1}, w2:, {w2}, bias:, {bias}, loss:, {loss}')
                break

        return w1, w2, bias


    

In [52]:
CustomModel = myNN()
CustomModel.fit(X_train_scaled, y_train, epochs = 500, loss_thresold = 0.4923)

Epoch:0, w1:, 0.9736899318847281, w2:, 0.931388810977659, bias:, -0.11748951666770448, loss:, 0.7428288579142563
Epoch:50, w1:, 1.5242798722391318, w2:, 0.8822187836689881, bias:, -1.1310088596841466, loss:, 0.5943161377198863
Epoch:100, w1:, 2.228187036337397, w2:, 1.0212075704807773, bias:, -1.5219348336892933, loss:, 0.5674253359204207
Epoch:150, w1:, 2.878880202063386, w2:, 1.0918966282424583, bias:, -1.8376731064036331, loss:, 0.5462065237139113
Epoch:200, w1:, 3.473286412049912, w2:, 1.1354958313845407, bias:, -2.109494376761035, loss:, 0.5289749850551891
Epoch:250, w1:, 4.014235251285109, w2:, 1.168307211546194, bias:, -2.3515205001257873, loss:, 0.5148317335261617
Epoch:300, w1:, 4.506491403088422, w2:, 1.1967920767703706, bias:, -2.570834600613761, loss:, 0.5031414005690805
Epoch:350, w1:, 4.955154772161111, w2:, 1.2234470550440066, bias:, -2.7714756232427904, loss:, 0.4934177492028928
Epoch:357, w1:, 5.0147687108051695, w2:, 1.227094212784905, bias:, -2.7982358620493586, loss

In [54]:
coef, intercept

(array([[5.018309 ],
        [1.1966311]], dtype=float32),
 array([-2.766541], dtype=float32))

In [55]:
CustomModel.predict(X_test_scaled)

9     0.815758
25    0.757098
8     0.823176
21    0.183263
0     0.385115
12    0.190888
dtype: float64

In [56]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step


array([[0.81626713],
       [0.7576754 ],
       [0.82367426],
       [0.18819512],
       [0.38559145],
       [0.19598222]], dtype=float32)